import type { EmailAnalysis, EmailContext, Language, SuggestedAction } from "@oao/shared";
import { normalizeWhitespace, truncate } from "../util/text.js";
import { detectLanguage } from "./language.js";

/**
 * Triage — the first and cheapest line of AI-load minimisation.
 *
 * Every inbound email is classified here, with **pure heuristics only**, before
 * any model call. Only `conversation` emails are worth a model call; for every
 * other kind the orchestrator answers from `triageAnalysis()` below
 * (`source: "heuristic"`), which costs zero GPU time.
 *
 * Inputs are the fields the add-in / Graph always give us: sender, subject,
 * body text, attachment metadata and Outlook categories. `EmailContext` carries
 * no raw MIME headers, so header-level signals (`List-Unsubscribe`,
 * `Auto-Submitted`, `X-Auto-Response-Suppress`, `Content-Type: text/calendar`)
 * are recognised through their body/sender/attachment equivalents — Outlook and
 * Graph surface them as visible footers, sender conventions and `.ics` parts.
 *
 * Ordering matters: the more specific a kind, the earlier it is tested.
 * An out-of-office reply from `noreply@` is an out-of-office, not a notification.
 */

export type TriageKind = NonNullable<EmailAnalysis["triage"]>["kind"];

export interface TriageResult {
  kind: TriageKind;
  /** Short machine-readable reason, e.g. `sender:noreply` or `body:unsubscribe`. */
  reason: string;
  /** Honest confidence of the *classification* (not of the summary). */
  confidence: number;
  /** True when no model call is needed. */
  skipModel: boolean;
}

/** Sender local-parts that never expect a human reply. */
const ROBOT_LOCALPARTS = [
  "noreply",
  "no-reply",
  "no_reply",
  "donotreply",
  "do-not-reply",
  "do_not_reply",
  "nepasrepondre",
  "ne-pas-repondre",
  "notifications",
  "notification",
  "notifier",
  "alerts",
  "alert",
  "automated",
  "autoreply",
  "auto-reply",
  "mailer-daemon",
  "postmaster",
  "bounce",
  "bounces",
  "system",
  "sysadmin",
  "root",
  "daemon",
];

/** Body / footer markers equivalent to a `List-Unsubscribe` header. */
const UNSUBSCRIBE_MARKERS = [
  "unsubscribe",
  "un-subscribe",
  "désabonner",
  "desabonner",
  "ne plus recevoir",
  "ne souhaitez plus recevoir",
  "désabonnement",
  "desabonnement",
  "désinscrire",
  "desinscrire",
  "list-unsubscribe",
  "manage your preferences",
  "manage your subscription",
  "email preferences",
  "gérer vos préférences",
  "gerer vos preferences",
  "view in browser",
  "view this email in your browser",
  "voir dans le navigateur",
  "afficher dans le navigateur",
  "vous recevez cet email",
  "vous recevez ce message",
  "you are receiving this email because",
  "you received this email because",
  "update your profile",
];

const NEWSLETTER_LOCALPARTS = ["newsletter", "news", "marketing", "campaign", "campaigns", "mailing", "communication", "communications", "press", "media", "hello", "promo", "promotions", "events", "webinar"];

/** Auto-reply / absence markers (FR + EN). */
const OOO_MARKERS = [
  "out of office",
  "out of the office",
  "outofoffice",
  "ooo:",
  "automatic reply",
  "auto-reply",
  "autoreply",
  "auto reply",
  "away from my desk",
  "on annual leave",
  "on parental leave",
  "i am currently away",
  "i will be out",
  "absent du bureau",
  "absence du bureau",
  "actuellement absent",
  "actuellement absente",
  "je suis absent",
  "je suis absente",
  "réponse automatique",
  "reponse automatique",
  "en congé",
  "en conge",
  "en vacances",
  "de retour le",
  "back in the office on",
];

/** Generic "this was generated by a machine" markers (`Auto-Submitted: auto-generated`). */
const AUTOMATIC_MARKERS = [
  "this is an automated message",
  "this is an automatic message",
  "automatically generated",
  "auto-generated",
  "autogenerated",
  "do not reply to this email",
  "do not reply to this message",
  "please do not reply",
  "message généré automatiquement",
  "message genere automatiquement",
  "généré automatiquement",
  "genere automatiquement",
  "ne pas répondre à ce message",
  "ne pas repondre a ce message",
  "merci de ne pas répondre",
  "ceci est un message automatique",
  "delivery status notification",
  "undeliverable",
  "read receipt",
  "accusé de réception",
  "accuse de reception",
];

/** Calendar invite markers (`Content-Type: text/calendar`, Outlook invite bodies). */
const CALENDAR_SUBJECT_PREFIXES = [
  "invitation:",
  "accepted:",
  "declined:",
  "tentative:",
  "canceled:",
  "cancelled:",
  "updated invitation:",
  "invitation modifiée",
  "invitation annulée",
  "acceptée :",
  "refusée :",
  "réunion annulée",
  "fw: invitation:",
  "re: invitation:",
];

const CALENDAR_BODY_MARKERS = ["begin:vcalendar", "microsoft teams meeting", "join the meeting", "rejoindre la réunion", "réunion microsoft teams", "join zoom meeting", "when:", "quand :", "organizer:", "organisateur :"];

/** Very short acknowledgements that carry no content to analyse. */
const TRIVIAL_PATTERNS: RegExp[] = [
  /^(many\s+)?thanks?(\s+(a lot|so much|very much|again|all))?[.!]*$/i,
  /^thank you(\s+(very much|so much|all|again))?[.!]*$/i,
  /^(ok|okay|oki|okey)([.!]*|,?\s*(thanks|thx|merci)[.!]*)$/i,
  /^(noted|well noted|duly noted|received|got it|understood|acknowledged|will do|sounds good|perfect|great|excellent)[.!]*$/i,
  /^merci(\s+(beaucoup|bien|à vous|a vous|d'avance|davance|encore))?[.!]*$/i,
  /^(bien reçu|bien recu|reçu|recu|noté|note|c'est noté|cest note|entendu|parfait|très bien|tres bien|d'accord|daccord|ça marche|ca marche)[.!]*$/i,
  /^(ci-joint|voir ci-dessous|see below|fyi|pour info|pour information)[.!]*$/i,
  /^\+1[.!]*$/,
];

/**
 * Greeting and sign-off lines, stripped before measuring "how short is this
 * really". Both require a *short* remainder and no question mark, so
 * "Thanks — can you confirm the deadline?" stays: it is a real question that
 * happens to open with a courtesy word.
 */
const GREETING_LINE = /^(bonjour|bonsoir|salut|hello|hi|hey|dear|cher|chère|chers|coucou|good (morning|afternoon|evening))\b[^?]{0,40}$/i;
/**
 * A sign-off line: a closing word followed by punctuation or at most a dozen
 * characters. The tight remainder is what separates "Merci." (a sign-off) from
 * "Thanks, here is the document you asked for." (content that opens politely).
 * Everything after a sign-off is a signature block, so scanning stops there.
 */
const SIGNOFF_LINE =
  /^(merci|thanks|thx|thank you|regards|best regards|kind regards|warm regards|cordialement|bien cordialement|sincèrement|sincerely|meilleures salutations|salutations|cheers|bien à vous|bien a vous)\b[^?!]{0,12}$|^(envoyé de mon|envoye de mon|sent from my|get outlook for|obtenez outlook pour)\b.{0,40}$|^(--+|__+)$/i;

export interface TriageOptions {
  /** Domains considered internal; internal senders are never triaged as newsletters. */
  internalDomains?: string[];
}

const localPart = (address: string | undefined): string => (address ?? "").toLowerCase().split("@")[0] ?? "";
const hasAny = (haystack: string, needles: string[]): string | undefined => needles.find((n) => haystack.includes(n));

/** Body with greetings, sign-offs, signature names and empty lines removed — what is actually said. */
export function coreBodyText(body: string): string {
  const lines = normalizeWhitespace(body)
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  const kept: string[] = [];
  for (const line of lines) {
    if (GREETING_LINE.test(line)) continue;
    // A sign-off ends the message: what follows is a signature, not content.
    if (SIGNOFF_LINE.test(line)) break;
    kept.push(line);
  }
  return kept.join(" ").trim();
}

/** Classify an email with pure heuristics. Never throws, never does I/O. */
export function triageEmail(email: EmailContext, opts: TriageOptions = {}): TriageResult {
  const subject = (email.subject ?? "").trim();
  const subjectLower = subject.toLowerCase();
  const body = email.body ?? "";
  const bodyLower = body.toLowerCase();
  const all = `${subjectLower}\n${bodyLower}`;
  const sender = (email.from?.address ?? "").toLowerCase();
  const local = localPart(sender);
  const attachmentNames = email.attachments.map((a) => (a.name ?? "").toLowerCase());
  const attachmentTypes = email.attachments.map((a) => (a.contentType ?? "").toLowerCase());
  const categories = email.categories.map((c) => c.toLowerCase());

  const conv = (reason: string, confidence = 0.6): TriageResult => ({ kind: "conversation", reason, confidence, skipModel: false });
  const skip = (kind: TriageKind, reason: string, confidence: number): TriageResult => ({ kind, reason, confidence, skipModel: true });

  /* 1. Out of office / auto-reply — the sender is a human but nothing is asked. */
  const oooSubject = hasAny(subjectLower, OOO_MARKERS);
  if (oooSubject) return skip("out_of_office", `subject:${oooSubject}`, 0.85);
  const oooBody = hasAny(bodyLower.slice(0, 600), OOO_MARKERS);
  if (oooBody && body.length < 1500) return skip("out_of_office", `body:${oooBody}`, 0.7);

  /* 2. Calendar invites / responses. */
  if (attachmentTypes.some((t) => t.includes("text/calendar")) || attachmentNames.some((n) => n.endsWith(".ics"))) return skip("calendar", "attachment:ics", 0.9);
  const calPrefix = CALENDAR_SUBJECT_PREFIXES.find((p) => subjectLower.startsWith(p));
  if (calPrefix) return skip("calendar", `subject:${calPrefix}`, 0.8);
  if (bodyLower.includes("begin:vcalendar")) return skip("calendar", "body:vcalendar", 0.9);
  const calMarkers = CALENDAR_BODY_MARKERS.filter((m) => bodyLower.includes(m));
  if (calMarkers.length >= 2 && /\b(meeting|réunion|reunion|invitation|appointment|rendez-vous)\b/i.test(all)) return skip("calendar", `body:${calMarkers.slice(0, 2).join("+")}`, 0.65);

  /* 3. Newsletters / marketing (List-Unsubscribe equivalents). */
  const unsub = hasAny(bodyLower, UNSUBSCRIBE_MARKERS);
  const internal = isInternal(sender, opts.internalDomains ?? []);
  if (unsub && !internal) return skip("newsletter", `body:${unsub}`, 0.85);
  if (unsub && internal && NEWSLETTER_LOCALPARTS.includes(local)) return skip("newsletter", `internal-sender:${local}`, 0.7);
  if (!internal && NEWSLETTER_LOCALPARTS.includes(local) && /\b(newsletter|weekly|monthly|digest|bulletin|webinar|webinaire|invitation to|promotion|offre|discover|découvrez)\b/i.test(all)) {
    return skip("newsletter", `sender:${local}`, 0.65);
  }
  if (categories.some((c) => c.includes("newsletter"))) return skip("newsletter", "category:newsletter", 0.6);

  /* 4. Machine-generated messages (delivery reports, "do not reply"). */
  const autoMarker = hasAny(all, AUTOMATIC_MARKERS);
  if (autoMarker) return skip("automatic", `body:${autoMarker}`, 0.75);

  /* 5. System notifications from a robot sender. */
  const robot = ROBOT_LOCALPARTS.find((r) => local === r || local.startsWith(`${r}.`) || local.startsWith(`${r}-`) || local.startsWith(`${r}_`) || local.includes(r));
  if (robot) return skip("notification", `sender:${robot}`, 0.8);
  if (/^\s*\[(?:[\w .-]{2,24})\]/.test(subject) && !internal && /\b(ticket|issue|alert|alerte|build|deploy|incident|case|request #|jira|servicenow)\b/i.test(all)) {
    return skip("notification", "subject:tagged-system", 0.6);
  }

  /* 6. Trivial acknowledgements — nothing to summarise. */
  const core = coreBodyText(body);
  const hasAttachment = email.attachments.some((a) => !a.isInline);
  if (!hasAttachment && !core.includes("?")) {
    if (core.length === 0 && subject.length > 0) return skip("trivial", "body:empty", 0.6);
    if (core.length <= 160 && TRIVIAL_PATTERNS.some((re) => re.test(core.replace(/\s+/g, " ").trim()))) return skip("trivial", "body:acknowledgement", 0.75);
    if (core.length <= 25) return skip("trivial", "body:too-short", 0.55);
  }

  return conv("default", 0.6);
}

function isInternal(address: string, internalDomains: string[]): boolean {
  const at = address.lastIndexOf("@");
  if (at < 0) return false;
  const domain = address.slice(at + 1);
  return internalDomains.some((d) => {
    const dd = d.toLowerCase();
    return domain === dd || domain.endsWith(`.${dd}`);
  });
}

/* ------------------------------------------------------------------------- */
/*  Heuristic answer for non-conversation emails (no model call)             */
/* ------------------------------------------------------------------------- */

/** Shape of an analysis before the service adds `auditId` / `generatedAt`. */
export interface TriageAnalysis {
  language: Language;
  summary: string;
  decisions: string[];
  pendingTasks: string[];
  risks: EmailAnalysis["risks"];
  suggestedActions: SuggestedAction[];
  quickReplies: string[];
  classification: { category: string; confidence: number };
  /** Confidence of the produced *analysis* — deliberately modest. */
  confidence: number;
}

const CATEGORY: Record<TriageKind, { fr: string; en: string }> = {
  conversation: { fr: "Général", en: "General" },
  notification: { fr: "Notification système", en: "System notification" },
  newsletter: { fr: "Newsletter", en: "Newsletter" },
  out_of_office: { fr: "Absence", en: "Out of office" },
  automatic: { fr: "Message automatique", en: "Automatic message" },
  calendar: { fr: "Réunion", en: "Meeting" },
  trivial: { fr: "Accusé de réception", en: "Acknowledgement" },
};

/** Summary templates. `%s` = sender, `%t` = subject. */
const SUMMARY: Record<TriageKind, { fr: string; en: string }> = {
  conversation: {
    fr: "%s écrit au sujet de « %t ».",
    en: '%s writes regarding "%t".',
  },
  notification: {
    fr: "Notification automatique de %s : « %t ». Aucune réponse attendue — classée sans analyse IA.",
    en: 'Automated notification from %s: "%t". No reply expected — filed without an AI analysis.',
  },
  newsletter: {
    fr: "Newsletter / communication marketing de %s : « %t ». Aucune action requise ; à lire ou archiver.",
    en: 'Newsletter / marketing message from %s: "%t". No action required; read or archive.',
  },
  out_of_office: {
    fr: "Réponse automatique d'absence de %s (« %t »). Relancer après son retour si le sujet reste ouvert.",
    en: 'Out-of-office auto-reply from %s ("%t"). Follow up after their return if the matter is still open.',
  },
  automatic: {
    fr: "Message généré automatiquement par %s : « %t ». Ne pas répondre.",
    en: 'Machine-generated message from %s: "%t". Do not reply.',
  },
  calendar: {
    fr: "Élément de calendrier de %s : « %t ». À traiter dans le calendrier Outlook (accepter, refuser ou proposer un autre créneau).",
    en: 'Calendar item from %s: "%t". Handle it in the Outlook calendar (accept, decline or propose another slot).',
  },
  trivial: {
    fr: "Court accusé de réception de %s au sujet de « %t ». Aucune action requise.",
    en: 'Short acknowledgement from %s regarding "%t". No action required.',
  },
};

/** Confidence per kind: honest — the classification is solid, the summary is a template. */
const CONFIDENCE: Record<TriageKind, number> = {
  conversation: 0.6,
  notification: 0.5,
  newsletter: 0.55,
  out_of_office: 0.55,
  automatic: 0.5,
  calendar: 0.5,
  trivial: 0.45,
};

/**
 * Heuristic-only analysis for a triaged (non-conversation) email.
 * Deterministic, pure, and produced without any model call.
 */
export function triageAnalysis(email: EmailContext, triage: TriageResult, preferred?: Language): TriageAnalysis {
  const language = preferred ?? detectLanguage(`${email.subject}\n${email.body}`, "en");
  const fr = language === "fr";
  const sender = email.from?.name || email.from?.address || (fr ? "Un expéditeur inconnu" : "An unknown sender");
  const subject = email.subject?.trim() || (fr ? "(sans objet)" : "(no subject)");
  const template = SUMMARY[triage.kind];
  const summary = (fr ? template.fr : template.en).replace("%s", sender).replace("%t", truncate(subject, 120));
  const category = fr ? CATEGORY[triage.kind].fr : CATEGORY[triage.kind].en;

  const suggestedActions: SuggestedAction[] = [
    { type: "categorize", title: fr ? `Classer comme « ${category} »` : `File as "${category}"`, description: fr ? "Appliquer la catégorie déduite par le tri heuristique" : "Apply the category inferred by heuristic triage", parameters: { category, triage: triage.kind } },
  ];
  const pendingTasks: string[] = [];

  switch (triage.kind) {
    case "newsletter":
    case "notification":
    case "automatic":
      suggestedActions.push({ type: "archive", title: fr ? "Archiver" : "Archive", description: fr ? "Aucune réponse attendue : archiver le message" : "No reply expected: archive the message", parameters: {} });
      break;
    case "out_of_office":
      pendingTasks.push(fr ? `Relancer ${sender} après son retour.` : `Follow up with ${sender} after their return.`);
      suggestedActions.push({ type: "create_reminder", title: fr ? "Créer un rappel de relance" : "Create a follow-up reminder", description: fr ? "Planifier une relance après l'absence" : "Schedule a follow-up after the absence", parameters: { title: `${fr ? "Relance" : "Follow-up"}: ${truncate(subject, 80)}` } });
      break;
    case "calendar":
      pendingTasks.push(fr ? "Répondre à l'invitation dans le calendrier Outlook." : "Respond to the invitation in the Outlook calendar.");
      suggestedActions.push({ type: "flag", title: fr ? "Marquer pour suivi" : "Flag for follow-up", description: fr ? "Marquer l'invitation à traiter" : "Flag the invitation to handle", parameters: {} });
      break;
    case "trivial":
    case "conversation":
      break;
  }

  const risks: EmailAnalysis["risks"] = [];
  if (email.attachments.some((a) => !a.isInline) && (triage.kind === "notification" || triage.kind === "automatic" || triage.kind === "newsletter")) {
    risks.push({ code: "unexpected_attachment", title: fr ? "Pièce jointe sur un message automatique" : "Attachment on an automated message", severity: "medium", description: fr ? "Vérifier l'expéditeur avant d'ouvrir la pièce jointe." : "Verify the sender before opening the attachment." });
  }

  return {
    language,
    summary,
    decisions: [],
    pendingTasks,
    risks,
    suggestedActions,
    quickReplies: [],
    classification: { category, confidence: triage.confidence },
    confidence: CONFIDENCE[triage.kind],
  };
}
