{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) (not .Values.externalSecrets.enabled) }}
{{- $data := include "oao.secretData" . | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oao.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oao.componentLabels" (list . "orchestrator") | indent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
type: Opaque
{{- if $data }}
stringData:
{{ toYaml $data | indent 2 }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
